/**
 * ThoughtSpot Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateConnectionRequest {
    /**
    * Unique name for the connection.
    */
    'name': string;
    /**
    * Description of the connection.
    */
    'description'?: string;
    /**
    * Type of the data warehouse.
    */
    'data_warehouse_type': CreateConnectionRequestDataWarehouseTypeEnum;
    /**
    * Connection configuration attributes in JSON format. To create a connection with tables, include table attributes. See the documentation above for sample JSON.
    */
    'data_warehouse_config': any;
    /**
    * Validates the connection metadata if tables are included. If you are creating a connection without tables, specify `false`.
    */
    'validate'?: boolean | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "data_warehouse_type",
            "baseName": "data_warehouse_type",
            "type": "CreateConnectionRequestDataWarehouseTypeEnum",
            "format": ""
        },
        {
            "name": "data_warehouse_config",
            "baseName": "data_warehouse_config",
            "type": "any",
            "format": ""
        },
        {
            "name": "validate",
            "baseName": "validate",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateConnectionRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum CreateConnectionRequestDataWarehouseTypeEnum {
    Snowflake = 'SNOWFLAKE',
    AmazonRedshift = 'AMAZON_REDSHIFT',
    GoogleBigquery = 'GOOGLE_BIGQUERY',
    AzureSynapse = 'AZURE_SYNAPSE',
    Teradata = 'TERADATA',
    SapHana = 'SAP_HANA',
    Starburst = 'STARBURST',
    OracleAdw = 'ORACLE_ADW',
    Databricks = 'DATABRICKS',
    Denodo = 'DENODO',
    Dremio = 'DREMIO',
    Trino = 'TRINO',
    Presto = 'PRESTO',
    Postgres = 'POSTGRES',
    Sqlserver = 'SQLSERVER',
    Mysql = 'MYSQL',
    GenericJdbc = 'GENERIC_JDBC',
    AmazonRdsPostgresql = 'AMAZON_RDS_POSTGRESQL',
    AmazonAuroraPostgresql = 'AMAZON_AURORA_POSTGRESQL',
    AmazonRdsMysql = 'AMAZON_RDS_MYSQL',
    AmazonAuroraMysql = 'AMAZON_AURORA_MYSQL',
    Looker = 'LOOKER',
    AmazonAthena = 'AMAZON_ATHENA',
    Singlestore = 'SINGLESTORE',
    GcpSqlserver = 'GCP_SQLSERVER',
    GcpAlloydbPostgresql = 'GCP_ALLOYDB_POSTGRESQL',
    GcpPostgresql = 'GCP_POSTGRESQL',
    GcpMysql = 'GCP_MYSQL',
    Mode = 'MODE',
    GoogleSheets = 'GOOGLE_SHEETS',
    Falcon = 'FALCON',
    FalconOnprem = 'FALCON_ONPREM'
}

