/**
 * ThoughtSpot Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Filter Rules to be applied on Objects.
*/
export class FilterRules {
    /**
    * The name of the column to apply the filter on.
    */
    'column_name': string;
    /**
    * The operator to use for filtering. Example: EQ (equals), GT(greater than), etc.
    */
    'operator': FilterRulesOperatorEnum;
    /**
    * The values to filter on. To get all records, use TS_WILDCARD_ALL as values.
    */
    'values': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "column_name",
            "baseName": "column_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "FilterRulesOperatorEnum",
            "format": ""
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FilterRules.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum FilterRulesOperatorEnum {
    Eq = 'EQ',
    Ne = 'NE',
    Lt = 'LT',
    Le = 'LE',
    Gt = 'GT',
    Ge = 'GE',
    In = 'IN',
    Bw = 'BW',
    Contains = 'CONTAINS',
    BeginsWith = 'BEGINS_WITH',
    EndsWith = 'ENDS_WITH',
    BwInc = 'BW_INC',
    BwIncMin = 'BW_INC_MIN',
    BwIncMax = 'BW_INC_MAX',
    Like = 'LIKE',
    NotIn = 'NOT_IN'
}

