/**
 * ThoughtSpot Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GroupsImportListInput {
    /**
    * Unique display name of the group.
    */
    'display_name': string;
    /**
    * Unique ID or name of the group.
    */
    'group_identifier': string;
    /**
    * Unique ID of Liveboards that will be assigned as default Liveboards to the users in the group.
    */
    'default_liveboard_identifiers'?: Array<string> | null;
    /**
    * Description of the group.
    */
    'description'?: string | null;
    /**
    * Privileges that will be assigned to the group.
    */
    'privileges'?: Array<GroupsImportListInputPrivilegesEnum> | null;
    /**
    * Unique ID or name of the sub-groups to add to the group.
    */
    'sub_group_identifiers'?: Array<string> | null;
    /**
    * Type of the group.
    */
    'type'?: GroupsImportListInputTypeEnum | null;
    /**
    * Unique ID or name of the users to assign to the group.
    */
    'user_identifiers'?: Array<string> | null;
    /**
    * Visibility of the group. The SHARABLE makes a group visible to other users and groups, and thus allows them to share objects.
    */
    'visibility'?: GroupsImportListInputVisibilityEnum | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "display_name",
            "baseName": "display_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "group_identifier",
            "baseName": "group_identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "default_liveboard_identifiers",
            "baseName": "default_liveboard_identifiers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "privileges",
            "baseName": "privileges",
            "type": "Array<GroupsImportListInputPrivilegesEnum>",
            "format": ""
        },
        {
            "name": "sub_group_identifiers",
            "baseName": "sub_group_identifiers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "GroupsImportListInputTypeEnum",
            "format": ""
        },
        {
            "name": "user_identifiers",
            "baseName": "user_identifiers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "visibility",
            "baseName": "visibility",
            "type": "GroupsImportListInputVisibilityEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GroupsImportListInput.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum GroupsImportListInputPrivilegesEnum {
    Administration = 'ADMINISTRATION',
    Authoring = 'AUTHORING',
    Userdatauploading = 'USERDATAUPLOADING',
    Datadownloading = 'DATADOWNLOADING',
    Usermanagement = 'USERMANAGEMENT',
    Datamanagement = 'DATAMANAGEMENT',
    Sharewithall = 'SHAREWITHALL',
    Jobscheduling = 'JOBSCHEDULING',
    A3Analysis = 'A3ANALYSIS',
    Experimentalfeatureprivilege = 'EXPERIMENTALFEATUREPRIVILEGE',
    Bypassrls = 'BYPASSRLS',
    Ranalysis = 'RANALYSIS',
    Developer = 'DEVELOPER',
    UserAdministration = 'USER_ADMINISTRATION',
    GroupAdministration = 'GROUP_ADMINISTRATION',
    Syncmanagement = 'SYNCMANAGEMENT',
    CanCreateCatalog = 'CAN_CREATE_CATALOG',
    DisablePinboardCreation = 'DISABLE_PINBOARD_CREATION',
    LiveboardVerifier = 'LIVEBOARD_VERIFIER',
    PreviewThoughtspotSage = 'PREVIEW_THOUGHTSPOT_SAGE',
    CanManageVersionControl = 'CAN_MANAGE_VERSION_CONTROL',
    ThirdpartyAnalysis = 'THIRDPARTY_ANALYSIS',
    AllowNonEmbedFullAppAccess = 'ALLOW_NON_EMBED_FULL_APP_ACCESS',
    CanAccessAnalystStudio = 'CAN_ACCESS_ANALYST_STUDIO',
    CanManageAnalystStudio = 'CAN_MANAGE_ANALYST_STUDIO',
    PreviewDocumentSearch = 'PREVIEW_DOCUMENT_SEARCH',
    CanSetupVersionControl = 'CAN_SETUP_VERSION_CONTROL'
}
export enum GroupsImportListInputTypeEnum {
    LocalGroup = 'LOCAL_GROUP',
    LdapGroup = 'LDAP_GROUP'
}
export enum GroupsImportListInputVisibilityEnum {
    Sharable = 'SHARABLE',
    NonSharable = 'NON_SHARABLE'
}

