/**
 * ThoughtSpot Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Sort options.
*/
export class MetadataSearchSortOptions {
    /**
    * Name of the field to apply the sort on.
    */
    'field_name'?: MetadataSearchSortOptionsFieldNameEnum | null;
    /**
    * Sort order : ASC(Ascending) or DESC(Descending).
    */
    'order'?: MetadataSearchSortOptionsOrderEnum | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "field_name",
            "baseName": "field_name",
            "type": "MetadataSearchSortOptionsFieldNameEnum",
            "format": ""
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "MetadataSearchSortOptionsOrderEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MetadataSearchSortOptions.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum MetadataSearchSortOptionsFieldNameEnum {
    Name = 'NAME',
    DisplayName = 'DISPLAY_NAME',
    Author = 'AUTHOR',
    Created = 'CREATED',
    Modified = 'MODIFIED',
    Views = 'VIEWS',
    Favorites = 'FAVORITES',
    LastAccessed = 'LAST_ACCESSED'
}
export enum MetadataSearchSortOptionsOrderEnum {
    Asc = 'ASC',
    Desc = 'DESC'
}

