/**
 * ThoughtSpot Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserObject } from '../models/UserObject';
import { HttpFile } from '../http/http';

/**
* Objects to apply the Runtime_Filters.
*/
export class RuntimeFilters {
    /**
    * The column name to apply filter.
    */
    'column_name': string;
    /**
    * Value of the filters.
    */
    'values': Array<string>;
    /**
    * Operator value. Example: EQ
    */
    'operator': RuntimeFiltersOperatorEnum;
    /**
    * Flag to persist the runtime filters.    Version: 9.12.0.cl or later 
    */
    'persist'?: boolean | null;
    /**
    * Object to apply the runtime filter.
    */
    'objects'?: Array<UserObject> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "column_name",
            "baseName": "column_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "RuntimeFiltersOperatorEnum",
            "format": ""
        },
        {
            "name": "persist",
            "baseName": "persist",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "objects",
            "baseName": "objects",
            "type": "Array<UserObject>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RuntimeFilters.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum RuntimeFiltersOperatorEnum {
    Eq = 'EQ',
    Ne = 'NE',
    Lt = 'LT',
    Le = 'LE',
    Gt = 'GT',
    Ge = 'GE',
    In = 'IN',
    Bw = 'BW',
    Contains = 'CONTAINS',
    BeginsWith = 'BEGINS_WITH',
    EndsWith = 'ENDS_WITH',
    BwInc = 'BW_INC',
    BwIncMin = 'BW_INC_MIN',
    BwIncMax = 'BW_INC_MAX',
    Like = 'LIKE',
    NotIn = 'NOT_IN'
}

