/**
 * ThoughtSpot Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GenericInfo } from '../models/GenericInfo';
import { HttpFile } from '../http/http';

/**
* Response for search role api should handle hidden privileges as well.
*/
export class SearchRoleResponse {
    /**
    * Unique Id of the role.
    */
    'id': string;
    /**
    * Name of the role
    */
    'name': string;
    /**
    * Description of the role
    */
    'description': string;
    /**
    * number of groups assigned with this role
    */
    'groups_assigned_count'?: number | null;
    /**
    * Orgs in which role exists.
    */
    'orgs'?: Array<GenericInfo> | null;
    /**
    * Details of groups assigned with this role
    */
    'groups'?: Array<GenericInfo> | null;
    /**
    * Privileges granted to the role.
    */
    'privileges': Array<SearchRoleResponsePrivilegesEnum>;
    /**
    * Permission details of the Role
    */
    'permission'?: SearchRoleResponsePermissionEnum | null;
    /**
    * Unique identifier of author of the role.
    */
    'author_id'?: string | null;
    /**
    * Unique identifier of modifier of the role.
    */
    'modifier_id'?: string | null;
    /**
    * Creation time of the role in milliseconds.
    */
    'creation_time_in_millis'?: any | null;
    /**
    * Last modified time of the role in milliseconds.
    */
    'modification_time_in_millis'?: any | null;
    /**
    * Indicates whether the role is deleted.
    */
    'deleted'?: boolean | null;
    /**
    * Indicates whether the role is deprecated.
    */
    'deprecated'?: boolean | null;
    /**
    * Indicates whether the role is external.
    */
    'external'?: boolean | null;
    /**
    * Indicates whether the role is hidden.
    */
    'hidden'?: boolean | null;
    /**
    * Indicates whether the role is shared via connection
    */
    'shared_via_connection'?: boolean | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "groups_assigned_count",
            "baseName": "groups_assigned_count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "orgs",
            "baseName": "orgs",
            "type": "Array<GenericInfo>",
            "format": ""
        },
        {
            "name": "groups",
            "baseName": "groups",
            "type": "Array<GenericInfo>",
            "format": ""
        },
        {
            "name": "privileges",
            "baseName": "privileges",
            "type": "Array<SearchRoleResponsePrivilegesEnum>",
            "format": ""
        },
        {
            "name": "permission",
            "baseName": "permission",
            "type": "SearchRoleResponsePermissionEnum",
            "format": ""
        },
        {
            "name": "author_id",
            "baseName": "author_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "modifier_id",
            "baseName": "modifier_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "creation_time_in_millis",
            "baseName": "creation_time_in_millis",
            "type": "any",
            "format": ""
        },
        {
            "name": "modification_time_in_millis",
            "baseName": "modification_time_in_millis",
            "type": "any",
            "format": ""
        },
        {
            "name": "deleted",
            "baseName": "deleted",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "deprecated",
            "baseName": "deprecated",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "external",
            "baseName": "external",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hidden",
            "baseName": "hidden",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "shared_via_connection",
            "baseName": "shared_via_connection",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchRoleResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum SearchRoleResponsePrivilegesEnum {
    Unknown = 'UNKNOWN',
    Administration = 'ADMINISTRATION',
    Authoring = 'AUTHORING',
    Userdatauploading = 'USERDATAUPLOADING',
    Datadownloading = 'DATADOWNLOADING',
    Usermanagement = 'USERMANAGEMENT',
    Securitymanagement = 'SECURITYMANAGEMENT',
    Logicalmodeling = 'LOGICALMODELING',
    Datamanagement = 'DATAMANAGEMENT',
    Tagmanagement = 'TAGMANAGEMENT',
    Sharewithall = 'SHAREWITHALL',
    Systemmanagement = 'SYSTEMMANAGEMENT',
    Jobscheduling = 'JOBSCHEDULING',
    A3Analysis = 'A3ANALYSIS',
    Experimentalfeatureprivilege = 'EXPERIMENTALFEATUREPRIVILEGE',
    Bypassrls = 'BYPASSRLS',
    Ranalysis = 'RANALYSIS',
    DisablePinboardCreation = 'DISABLE_PINBOARD_CREATION',
    Developer = 'DEVELOPER',
    ApplicationAdministration = 'APPLICATION_ADMINISTRATION',
    UserAdministration = 'USER_ADMINISTRATION',
    GroupAdministration = 'GROUP_ADMINISTRATION',
    BackupAdministration = 'BACKUP_ADMINISTRATION',
    SystemInfoAdministration = 'SYSTEM_INFO_ADMINISTRATION',
    Enablespotappcreation = 'ENABLESPOTAPPCREATION',
    Syncmanagement = 'SYNCMANAGEMENT',
    OrgAdministration = 'ORG_ADMINISTRATION',
    RoleAdministration = 'ROLE_ADMINISTRATION',
    AuthenticationAdministration = 'AUTHENTICATION_ADMINISTRATION',
    BillingInfoAdministration = 'BILLING_INFO_ADMINISTRATION',
    PreviewThoughtspotSage = 'PREVIEW_THOUGHTSPOT_SAGE',
    LiveboardVerifier = 'LIVEBOARD_VERIFIER',
    CanManageCustomCalendar = 'CAN_MANAGE_CUSTOM_CALENDAR',
    CanCreateOrEditConnections = 'CAN_CREATE_OR_EDIT_CONNECTIONS',
    CanConfigureConnections = 'CAN_CONFIGURE_CONNECTIONS',
    CanManageWorksheetViewsTables = 'CAN_MANAGE_WORKSHEET_VIEWS_TABLES',
    CanManageVersionControl = 'CAN_MANAGE_VERSION_CONTROL',
    ThirdpartyAnalysis = 'THIRDPARTY_ANALYSIS',
    ControlTrustedAuth = 'CONTROL_TRUSTED_AUTH',
    CanCreateCatalog = 'CAN_CREATE_CATALOG',
    AllowNonEmbedFullAppAccess = 'ALLOW_NON_EMBED_FULL_APP_ACCESS',
    CanAccessAnalystStudio = 'CAN_ACCESS_ANALYST_STUDIO',
    CanManageAnalystStudio = 'CAN_MANAGE_ANALYST_STUDIO',
    PreviewDocumentSearch = 'PREVIEW_DOCUMENT_SEARCH',
    CanSetupVersionControl = 'CAN_SETUP_VERSION_CONTROL'
}
export enum SearchRoleResponsePermissionEnum {
    ReadOnly = 'READ_ONLY',
    Modify = 'MODIFY',
    NoAccess = 'NO_ACCESS'
}

