/**
 * ThoughtSpot Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DataWarehouseObjects } from '../models/DataWarehouseObjects';
import { HttpFile } from '../http/http';

export class SearchConnectionResponse {
    /**
    * Unique ID of the connection.
    */
    'id': string;
    /**
    * Name of the connection.
    */
    'name': string;
    /**
    * Description of the connection.
    */
    'description'?: string | null;
    /**
    * Type of data warehouse.
    */
    'data_warehouse_type': SearchConnectionResponseDataWarehouseTypeEnum;
    'data_warehouse_objects'?: DataWarehouseObjects;
    /**
    * Details of the connection.
    */
    'details'?: any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "data_warehouse_type",
            "baseName": "data_warehouse_type",
            "type": "SearchConnectionResponseDataWarehouseTypeEnum",
            "format": ""
        },
        {
            "name": "data_warehouse_objects",
            "baseName": "data_warehouse_objects",
            "type": "DataWarehouseObjects",
            "format": ""
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchConnectionResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum SearchConnectionResponseDataWarehouseTypeEnum {
    Snowflake = 'SNOWFLAKE',
    AmazonRedshift = 'AMAZON_REDSHIFT',
    GoogleBigquery = 'GOOGLE_BIGQUERY',
    AzureSynapse = 'AZURE_SYNAPSE',
    Teradata = 'TERADATA',
    SapHana = 'SAP_HANA',
    Starburst = 'STARBURST',
    OracleAdw = 'ORACLE_ADW',
    Databricks = 'DATABRICKS',
    Denodo = 'DENODO',
    Dremio = 'DREMIO',
    Trino = 'TRINO',
    Presto = 'PRESTO',
    Postgres = 'POSTGRES',
    Sqlserver = 'SQLSERVER',
    Mysql = 'MYSQL',
    GenericJdbc = 'GENERIC_JDBC',
    AmazonRdsPostgresql = 'AMAZON_RDS_POSTGRESQL',
    AmazonAuroraPostgresql = 'AMAZON_AURORA_POSTGRESQL',
    AmazonRdsMysql = 'AMAZON_RDS_MYSQL',
    AmazonAuroraMysql = 'AMAZON_AURORA_MYSQL',
    Looker = 'LOOKER',
    AmazonAthena = 'AMAZON_ATHENA',
    Singlestore = 'SINGLESTORE',
    GcpSqlserver = 'GCP_SQLSERVER',
    GcpAlloydbPostgresql = 'GCP_ALLOYDB_POSTGRESQL',
    GcpPostgresql = 'GCP_POSTGRESQL',
    GcpMysql = 'GCP_MYSQL',
    Mode = 'MODE',
    GoogleSheets = 'GOOGLE_SHEETS',
    Falcon = 'FALCON',
    FalconOnprem = 'FALCON_ONPREM'
}

