/**
 * ThoughtSpot Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SearchRolesRequest {
    /**
    * unique ID or name of the Roles
    */
    'role_identifiers'?: Array<string>;
    /**
    * Unique Id or name of the Organisation
    */
    'org_identifiers'?: Array<string>;
    /**
    * Unique Id or name of the User Group
    */
    'group_identifiers'?: Array<string>;
    /**
    * Privileges assigned to the Role. See [Documentation](https://developers.thoughtspot.com/docs/rbac#_role_categories_and_privileges)for supported roles privileges.
    */
    'privileges'?: Array<SearchRolesRequestPrivilegesEnum>;
    /**
    * Indicates whether the Role is deprecated.
    */
    'deprecated'?: boolean | null;
    /**
    * Indicates whether the Role is external
    */
    'external'?: boolean | null;
    /**
    * Indicates whether the Role is shared via connection
    */
    'shared_via_connection'?: boolean | null;
    /**
    * Permission details of the Role
    */
    'permissions'?: Array<SearchRolesRequestPermissionsEnum>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "role_identifiers",
            "baseName": "role_identifiers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "org_identifiers",
            "baseName": "org_identifiers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "group_identifiers",
            "baseName": "group_identifiers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "privileges",
            "baseName": "privileges",
            "type": "Array<SearchRolesRequestPrivilegesEnum>",
            "format": ""
        },
        {
            "name": "deprecated",
            "baseName": "deprecated",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "external",
            "baseName": "external",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "shared_via_connection",
            "baseName": "shared_via_connection",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "permissions",
            "baseName": "permissions",
            "type": "Array<SearchRolesRequestPermissionsEnum>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchRolesRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum SearchRolesRequestPrivilegesEnum {
    Unknown = 'UNKNOWN',
    Administration = 'ADMINISTRATION',
    Authoring = 'AUTHORING',
    Userdatauploading = 'USERDATAUPLOADING',
    Datadownloading = 'DATADOWNLOADING',
    Usermanagement = 'USERMANAGEMENT',
    Securitymanagement = 'SECURITYMANAGEMENT',
    Logicalmodeling = 'LOGICALMODELING',
    Datamanagement = 'DATAMANAGEMENT',
    Tagmanagement = 'TAGMANAGEMENT',
    Sharewithall = 'SHAREWITHALL',
    Systemmanagement = 'SYSTEMMANAGEMENT',
    Jobscheduling = 'JOBSCHEDULING',
    A3Analysis = 'A3ANALYSIS',
    Experimentalfeatureprivilege = 'EXPERIMENTALFEATUREPRIVILEGE',
    Bypassrls = 'BYPASSRLS',
    Ranalysis = 'RANALYSIS',
    DisablePinboardCreation = 'DISABLE_PINBOARD_CREATION',
    Developer = 'DEVELOPER',
    ApplicationAdministration = 'APPLICATION_ADMINISTRATION',
    UserAdministration = 'USER_ADMINISTRATION',
    GroupAdministration = 'GROUP_ADMINISTRATION',
    BackupAdministration = 'BACKUP_ADMINISTRATION',
    SystemInfoAdministration = 'SYSTEM_INFO_ADMINISTRATION',
    Enablespotappcreation = 'ENABLESPOTAPPCREATION',
    Syncmanagement = 'SYNCMANAGEMENT',
    OrgAdministration = 'ORG_ADMINISTRATION',
    RoleAdministration = 'ROLE_ADMINISTRATION',
    AuthenticationAdministration = 'AUTHENTICATION_ADMINISTRATION',
    BillingInfoAdministration = 'BILLING_INFO_ADMINISTRATION',
    PreviewThoughtspotSage = 'PREVIEW_THOUGHTSPOT_SAGE',
    LiveboardVerifier = 'LIVEBOARD_VERIFIER',
    CanManageCustomCalendar = 'CAN_MANAGE_CUSTOM_CALENDAR',
    CanCreateOrEditConnections = 'CAN_CREATE_OR_EDIT_CONNECTIONS',
    CanConfigureConnections = 'CAN_CONFIGURE_CONNECTIONS',
    CanManageWorksheetViewsTables = 'CAN_MANAGE_WORKSHEET_VIEWS_TABLES',
    CanManageVersionControl = 'CAN_MANAGE_VERSION_CONTROL',
    ThirdpartyAnalysis = 'THIRDPARTY_ANALYSIS',
    ControlTrustedAuth = 'CONTROL_TRUSTED_AUTH',
    CanCreateCatalog = 'CAN_CREATE_CATALOG',
    AllowNonEmbedFullAppAccess = 'ALLOW_NON_EMBED_FULL_APP_ACCESS',
    CanAccessAnalystStudio = 'CAN_ACCESS_ANALYST_STUDIO',
    CanManageAnalystStudio = 'CAN_MANAGE_ANALYST_STUDIO',
    PreviewDocumentSearch = 'PREVIEW_DOCUMENT_SEARCH',
    CanSetupVersionControl = 'CAN_SETUP_VERSION_CONTROL'
}
export enum SearchRolesRequestPermissionsEnum {
    ReadOnly = 'READ_ONLY',
    Modify = 'MODIFY',
    NoAccess = 'NO_ACCESS'
}

