/**
 * ThoughtSpot Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UpdateRoleRequest {
    /**
    * Name of the Role.
    */
    'name': string;
    /**
    * Description of the Role.
    */
    'description'?: string;
    /**
    * Privileges granted to the role. See [Documentation](https://developers.thoughtspot.com/docs/rbac#_role_categories_and_privileges)for supported roles privileges.
    */
    'privileges'?: Array<UpdateRoleRequestPrivilegesEnum>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "privileges",
            "baseName": "privileges",
            "type": "Array<UpdateRoleRequestPrivilegesEnum>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateRoleRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum UpdateRoleRequestPrivilegesEnum {
    Userdatauploading = 'USERDATAUPLOADING',
    Datadownloading = 'DATADOWNLOADING',
    Datamanagement = 'DATAMANAGEMENT',
    Sharewithall = 'SHAREWITHALL',
    Jobscheduling = 'JOBSCHEDULING',
    A3Analysis = 'A3ANALYSIS',
    Experimentalfeatureprivilege = 'EXPERIMENTALFEATUREPRIVILEGE',
    Bypassrls = 'BYPASSRLS',
    DisablePinboardCreation = 'DISABLE_PINBOARD_CREATION',
    Developer = 'DEVELOPER',
    ApplicationAdministration = 'APPLICATION_ADMINISTRATION',
    UserAdministration = 'USER_ADMINISTRATION',
    GroupAdministration = 'GROUP_ADMINISTRATION',
    SystemInfoAdministration = 'SYSTEM_INFO_ADMINISTRATION',
    Syncmanagement = 'SYNCMANAGEMENT',
    OrgAdministration = 'ORG_ADMINISTRATION',
    RoleAdministration = 'ROLE_ADMINISTRATION',
    AuthenticationAdministration = 'AUTHENTICATION_ADMINISTRATION',
    BillingInfoAdministration = 'BILLING_INFO_ADMINISTRATION',
    ControlTrustedAuth = 'CONTROL_TRUSTED_AUTH',
    Tagmanagement = 'TAGMANAGEMENT',
    LiveboardVerifier = 'LIVEBOARD_VERIFIER',
    CanManageCustomCalendar = 'CAN_MANAGE_CUSTOM_CALENDAR',
    CanCreateOrEditConnections = 'CAN_CREATE_OR_EDIT_CONNECTIONS',
    CanManageWorksheetViewsTables = 'CAN_MANAGE_WORKSHEET_VIEWS_TABLES',
    CanManageVersionControl = 'CAN_MANAGE_VERSION_CONTROL',
    ThirdpartyAnalysis = 'THIRDPARTY_ANALYSIS',
    CanCreateCatalog = 'CAN_CREATE_CATALOG',
    CanAccessAnalystStudio = 'CAN_ACCESS_ANALYST_STUDIO',
    CanManageAnalystStudio = 'CAN_MANAGE_ANALYST_STUDIO',
    PreviewDocumentSearch = 'PREVIEW_DOCUMENT_SEARCH'
}

